services:
  mongodb:
    image: mongo:7.0
    container_name: member-app-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: member-app-db-admin
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb

  backend-service:
    build: ./member-app
    container_name: member-app-backend
    ports:
      - "8083:8083"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: member_db
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: password
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      APP_JWT_SECRET: MySuperSecretKeyForTheModernizationChallenge123MustBeLongEnough
    depends_on:
      - mongodb

  member-app-ui:
    build: ./member-app-ui
    container_name: member-app-ui
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend-service

volumes:
  mongo-data: